services:
  gatus:
    image: twinproduction/gatus:latest
    ports:
      - "7777:8080"
    volumes:
      - ./config:/config
      - ./data:/data/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Kolkata
