version: "3.1"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.16-alpine
    container_name: uptime-kuma
    volumes:
        - ./kuma-data:/app/data
    ports:
        - 3001:3001
    restart: unless-stopped
